@tool
extends Node3D
## Runtime/editor helper generated by RuntimeRigBuilder for ROT_INIT.* bone chains.
## Reads two TransformHandle3D controls and applies their rotations to Skeleton3D bone poses every frame.
class_name RuntimeRigRotator

## Relative path from this driver to the Skeleton3D whose bone poses should be modified.
@export var skeleton_path: NodePath
## Bone name for the rotation-root/aim-control portion of the chain.
@export var root_bone_name: StringName
## Bone names that copy the ROT_CONTROL handle's local rotation for finger/tail-like chained bending.
@export var controlled_bone_names: PackedStringArray = []
## Relative path from this driver to the TransformHandle3D that controls chained local rotation.
@export var rot_control_path: NodePath
## Relative path from this driver to the TransformHandle3D that controls the root bone direction.
@export var aim_control_path: NodePath
## Enables/disables the per-frame bone pose update without removing generated rig nodes.
@export var enabled := true


## Starts processing in both editor and runtime contexts.
## Returns: nothing; enables _process so generated controls drive skeleton poses continuously.
func _ready() -> void:
	set_process(true)


## Applies current TransformHandle3D rotations onto configured skeleton bones.
## _delta: frame time supplied by Godot; unused because this is a direct pose copy, not interpolation.
## Returns: nothing; skips missing skeletons, controls, or bone names safely.
func _process(_delta: float) -> void:
	if not enabled:
		return
	
	var skeleton := get_node_or_null(skeleton_path) as Skeleton3D
	if skeleton == null:
		return
	
	var rot_control := get_node_or_null(rot_control_path) as TransformHandle3D
	if rot_control:
		var rotation := rot_control.transform.basis.get_rotation_quaternion()
		for bone_name in controlled_bone_names:
			var bone_idx := skeleton.find_bone(bone_name)
			if bone_idx >= 0:
				skeleton.set_bone_pose_rotation(bone_idx, rotation)
	
	var aim_control := get_node_or_null(aim_control_path) as TransformHandle3D
	if aim_control and root_bone_name != &"":
		var root_idx := skeleton.find_bone(root_bone_name)
		if root_idx >= 0:
			skeleton.set_bone_pose_rotation(root_idx, aim_control.transform.basis.get_rotation_quaternion())
